-- ==========================================
-- Supabase Schema para Flappy Bird IoT
-- ==========================================

-- ------------------------------------------
-- 1. Tabla de Puntuaciones (Dashboard)
-- ------------------------------------------
create table public.scores (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar seguridad de nivel de fila (RLS) pública para lectura/escritura
alter table public.scores enable row level security;
create policy "Allow public read access" on public.scores for select using (true);
create policy "Allow public insert access" on public.scores for insert with check (true);


-- ------------------------------------------
-- 2. Tabla de Prueba (project-espnow)
-- ------------------------------------------
create table public.test_table (
  id uuid default gen_random_uuid() primary key,
  mensaje text,
  creado_en timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar seguridad de nivel de fila (RLS) pública para la tabla de prueba
alter table public.test_table enable row level security;
create policy "Allow public read access" on public.test_table for select using (true);
create policy "Allow public insert access" on public.test_table for insert with check (true);
